import sys
import os
from PIL import Image, ImageFont, ImageDraw

# --- CONFIGURATION ---
FONT_FILE = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" # Default Ubuntu font
FONT_SIZE = 14 # Size in points
OUTPUT_FILE = "main/fonts_pro.h"
FONT_NAME = "MyFontPro"
# ---------------------

def get_font_path():
    # Try to find a font if the default doesn't exist
    if os.path.exists(FONT_FILE):
        return FONT_FILE
    
    # Fallback search for common Linux fonts
    common_paths = [
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "arial.ttf"
    ]
    for p in common_paths:
        if os.path.exists(p):
            return p
    
    print(f"❌ Error: Could not find font file at {FONT_FILE}")
    print("Please edit the FONT_FILE path in the script to point to a valid .ttf file.")
    sys.exit(1)

def main():
    font_path = get_font_path()
    print(f"🔄 Processing font: {font_path} @ {FONT_SIZE}pt")
    
    try:
        font = ImageFont.truetype(font_path, FONT_SIZE)
    except Exception as e:
        print(f"❌ Error loading font: {e}")
        sys.exit(1)

    start_char = 32  # Space
    end_char = 126   # ~
    
    bitmaps = []
    glyphs = []
    bitmap_offset = 0
    
    print("⚡ Generating bitmaps...")

    for i in range(start_char, end_char + 1):
        char = chr(i)
        
        # specific fix for space char which has no bounding box
        if char == ' ':
            advance = font.getlength(' ')
            glyphs.append({
                'offset': bitmap_offset,
                'w': 0, 'h': 0,
                'x_adv': int(advance),
                'x_off': 0, 'y_off': 0
            })
            continue

        # Get bounding box and render
        bbox = font.getbbox(char)
        if not bbox:
            # Handle invisible chars
            glyphs.append({'offset': bitmap_offset, 'w': 0, 'h': 0, 'x_adv': 5, 'x_off': 0, 'y_off': 0})
            continue

        width = bbox[2] - bbox[0]
        height = bbox[3] - bbox[1]
        
        # Create image for char
        img = Image.new('1', (width, height), 0)
        draw = ImageDraw.Draw(img)
        draw.text((-bbox[0], -bbox[1]), char, font=font, fill=1)
        
        # Convert to bitstream (row major)
        pixels = list(img.getdata())
        current_byte = 0
        bit_cnt = 0
        
        for p in pixels:
            if p:
                current_byte |= (0x80 >> bit_cnt)
            
            bit_cnt += 1
            if bit_cnt == 8:
                bitmaps.append(current_byte)
                bitmap_offset += 1
                current_byte = 0
                bit_cnt = 0
        
        # Flush remaining bits
        if bit_cnt > 0:
            bitmaps.append(current_byte)
            bitmap_offset += 1

        # Metrics
        advance = font.getlength(char)
        # Note: y_off is usually negative because 0 is baseline
        glyphs.append({
            'offset': bitmap_offset - ((width * height + 7) // 8), # Calculate offset start
            'w': width,
            'h': height,
            'x_adv': int(advance),
            'x_off': bbox[0],
            'y_off': bbox[1] 
        })

    # --- WRITE HEADER FILE ---
    print(f"💾 Writing to {OUTPUT_FILE}...")
    
    with open(OUTPUT_FILE, "w") as f:
        f.write(f"// Generated by ttf_to_c.py\n")
        f.write(f"#ifndef FONTS_PRO_H\n#define FONTS_PRO_H\n\n")
        f.write(f"#include <stdint.h>\n#include <Arduino.h>\n\n")
        
        # Structs
        f.write("typedef struct {\n")
        f.write("    uint16_t bitmapOffset;\n")
        f.write("    uint8_t  width;\n")
        f.write("    uint8_t  height;\n")
        f.write("    uint8_t  xAdvance;\n")
        f.write("    int8_t   xOffset;\n")
        f.write("    int8_t   yOffset;\n")
        f.write("} GFXglyph;\n\n")
        
        f.write("typedef struct {\n")
        f.write("    uint8_t  *bitmap;\n")
        f.write("    GFXglyph *glyph;\n")
        f.write("    uint8_t   first, last;\n")
        f.write("    uint8_t   yAdvance;\n")
        f.write("} GFXfont;\n\n")

        # Bitmap Array
        f.write(f"static const uint8_t PROGMEM {FONT_NAME}Bitmaps[] = {{\n")
        for i, b in enumerate(bitmaps):
            f.write(f"0x{b:02X}, ")
            if (i + 1) % 12 == 0: f.write("\n    ")
        f.write("\n};\n\n")

        # Glyph Array
        f.write(f"static const GFXglyph PROGMEM {FONT_NAME}Glyphs[] = {{\n")
        for i, g in enumerate(glyphs):
            char_desc = repr(chr(start_char + i))
            f.write(f"    {{ {g['offset']}, {g['w']}, {g['h']}, {g['x_adv']}, {g['x_off']}, {g['y_off']} }}, // {char_desc}\n")
        f.write("};\n\n")

        # Font Struct
        # Calculate roughly font height for yAdvance
        y_adv = int(font.getmetrics()[0] + font.getmetrics()[1]) # ascent + descent
        
        f.write(f"static const GFXfont {FONT_NAME} = {{\n")
        f.write(f"    (uint8_t *){FONT_NAME}Bitmaps,\n")
        f.write(f"    (GFXglyph *){FONT_NAME}Glyphs,\n")
        f.write(f"    {start_char}, {end_char}, {y_adv}\n")
        f.write("};\n\n")
        
        f.write("#endif // FONTS_PRO_H\n")

    print("✅ Done! Font header created.")

if __name__ == "__main__":
    main()